### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by olefasting** [PotatoTech/fishsticks#16]
@PotatoTech 

I want to publish [rust-rpg-toolkit](https://github.com/olefasting/rust_rpg_toolkit) to `crates.io` but that is currently not possible as they do not allow crates to have git as the sole source for any of their dependencies.

I made some additions to `Cargo.toml` in #15, in preparation for publishing and if you have no objections to publishing now, I can do it, as I have everything set up for it. As it is your project, you might want to do it yourself, though, so you get ownership...

**Comment by PotatoTech** [comment]
I have now published the crate on `crates.io`.
