### ISSUE TITLE
Add an Error type

### ISSUE THREAD

**Issue by olefasting** [PotatoTech/fishsticks#9]
I have introduced an error type in FishFight, so that we can convert remote errors into this type, to make it less of a hassle to work with all the various Error types in the various dependencies. It would therefore be helpful to have an Error type in fishsticks, so that I can set the appropriate `ErrorKind` for these errors in the `From` implementation used to convert into FishFight error. This does not need to be anything comprehensive; I believe a `type Error = &'static str` will suffice.

I'll create a PR for this

**Comment by PotatoTech** [comment]
I pushed the changes, so you should be good to go.
